my_todo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_todo_app.urls'))
]

my_todo_app/urls.py
from django.urls import path
from . import views

app_name = 'salah'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('delete/<int:todo_id>', views.delete, name='delete')

]

my_todo_app/models.py
from django.db import models

# Create your models here.

class TodoList(models.Model):
    my_todo = models.CharField(max_length=300)
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.my_todo

my_todo_app/views.py
from re import X
from django.shortcuts import render
from .models import TodoList
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse

#Hello programmers, this is nothing but some tests to make sure that Git is Working...


def index(request):
    todo_list = TodoList.objects.order_by('-pub_date')[:5]
    context = {'todo_list':todo_list}
    return render(request, 'my_todo_app/index.html', context)

#Add Items In The Database
def add(request):
    x = request.POST['todo']
    time = timezone.now()
    if x != '':
        TodoList.objects.create(my_todo=x, pub_date=time)
    return HttpResponseRedirect(reverse('salah:index'))


#Delete Items In The Database
def delete(request, todo_id):
    item = TodoList.objects.get(pk=todo_id)
    item.delete()
    return HttpResponseRedirect(reverse('salah:index'))

my_todo_app/templates/my_todo_app/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" href="{% static 'my_todo_app/style.css' %}">
        
    <title>Todo List</title>
</head>
<body>
    <h1>Todo Lsit:</h1>
    <form action="{% url 'salah:add' %}" method="POST">
        {%csrf_token%}
        <input type="text" name="todo">
        <input type="submit" value="Add">
    </form>
    <h1> {{x}} </h1>
    {% if todo_list %}
    {% for todo in todo_list %}
    
        <h1 style="color:yellow;">- {{todo.my_todo}} <a href="{% url 'salah:delete' todo.id %}" style="margin-left: 20px;"> Delete {{todo.id}}</a> </h4>
    

    {% endfor %}
    {%else %}
    <h1 style="color:blue">Zero item in the datebase</h4>
    {% endif %}
</body>
</html>